/*flexberryautogenerated="true"*/
namespace IIS.ThermoObjectTask6
{
    using System;
    using ICSSoft.STORMNET.Web.Controls;

    using Resources;

    public partial class ОбъектыТеплопотребленияL : BaseListForm<ОбъектТеплопотребления>
    {
        /// <summary>
        /// Конструктор без параметров,
        /// инициализирует свойства, соответствующие конкретной форме.
        /// </summary>
        public ОбъектыТеплопотребленияL() : base(ОбъектТеплопотребления.Views.ОбъектТеплопотребленияL)
        {
            EditPage = ОбъектыТеплопотребленияE.FormPath;
        }
                
        /// <summary>
        /// Путь до формы.
        /// </summary>
        public static string FormPath
        {
            get { return "~/forms/ObektTeplopotrebleniya/ObektyTeplopotrebleniyaL.aspx"; }
        }

        /// <summary>
        /// Вызывается самым первым в Page_Load.
        /// </summary>
        protected override void Preload()
        {
        }

        /// <summary>
        /// Вызывается самым последним в Page_Load.
        /// </summary>
        protected override void Postload()
        {
        }
    }
}
