//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.ThermoObject
{
    using System;
    using System.Xml;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Ц бкод дубли у сплощади ОТ.
    /// </summary>
    // *** Start programmer edit section *** (ЦБкодДублиУСплощадиОТ CustomAttributes)

    // *** End programmer edit section *** (ЦБкодДублиУСплощадиОТ CustomAttributes)
    [ICSSoft.STORMNET.AccessType(ICSSoft.STORMNET.AccessType.none)]
    public class ЦБкодДублиУСплощадиОТ : ICSSoft.STORMNET.Business.BusinessServer
    {
        
        // *** Start programmer edit section *** (ЦБкодДублиУСплощадиОТ CustomMembers)

        // *** End programmer edit section *** (ЦБкодДублиУСплощадиОТ CustomMembers)

        
        // *** Start programmer edit section *** (OnUpdateОбъектТеплопотребления CustomAttributes)

        // *** End programmer edit section *** (OnUpdateОбъектТеплопотребления CustomAttributes)
        public virtual ICSSoft.STORMNET.DataObject[] OnUpdateОбъектТеплопотребления(IIS.ThermoObject.ОбъектТеплопотребления UpdatedObject)
        {
            // *** Start programmer edit section *** (OnUpdateОбъектТеплопотребления)

            return new ICSSoft.STORMNET.DataObject[0];
            // *** End programmer edit section *** (OnUpdateОбъектТеплопотребления)
        }
    }
}
