//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.ThermoObjectTask6
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET.Business;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Объект теплопотребления.
    /// </summary>
    // *** Start programmer edit section *** (ОбъектТеплопотребления CustomAttributes)

    // *** End programmer edit section *** (ОбъектТеплопотребления CustomAttributes)
    [BusinessServer("IIS.ThermoObjectTask6.ОбъектыТеплопотребленияBS, ThermoObjectTask6.BusinessServer" +
        "s", ICSSoft.STORMNET.Business.DataServiceObjectEvents.OnAllEvents)]
    [AutoAltered()]
    [Caption("Объект теплопотребления")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ОбъектТеплопотребленияE", new string[] {
            "Название as \'Название\'",
            "ДатаУстановки as \'Дата установки\'",
            "Здание as \'Здание\'",
            "Здание.Адрес as \'Адрес\'",
            "ЦБкод as \'Ц бкод\'",
            "Площадь as \'Площадь\'",
            "Потребитель as \'Потребитель\'",
            "Потребитель.НазваниеКомпании as \'Название компании\'"}, Hidden=new string[] {
            "ЦБкод"})]
    [AssociatedDetailViewAttribute("ОбъектТеплопотребленияE", "УчастокСети", "УчастокСетиE", true, "", "Участок сети", true, new string[] {
            ""})]
    [MasterViewDefineAttribute("ОбъектТеплопотребленияE", "Потребитель", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "НазваниеКомпании")]
    [View("ОбъектТеплопотребленияL", new string[] {
            "Название as \'Название\'",
            "ДатаУстановки as \'Дата установки\'",
            "ЦБкод as \'ЦБ код\'",
            "Площадь as \'Площадь\'",
            "Здание.Адрес as \'Адрес\'",
            "Здание.СетевойРайон.Название as \'Сетевой район\'",
            "Потребитель.НазваниеКомпании as \'Потребитель\'",
            "Потребитель.ЛицевойСчёт as \'Лицевой счёт потребителя\'"})]
    public class ОбъектТеплопотребления : ICSSoft.STORMNET.DataObject
    {
        
        private string fНазвание;
        
        private System.DateTime fДатаУстановки;
        
        private string fЦБкод;
        
        private double fПлощадь;
        
        private IIS.ThermoObjectTask6.Потребитель fПотребитель;
        
        private IIS.ThermoObjectTask6.DetailArrayOfУчастокСети fУчастокСети;
        
        private IIS.ThermoObjectTask6.Здание fЗдание;
        
        // *** Start programmer edit section *** (ОбъектТеплопотребления CustomMembers)

        // *** End programmer edit section *** (ОбъектТеплопотребления CustomMembers)

        
        /// <summary>
        /// Название.
        /// </summary>
        // *** Start programmer edit section *** (ОбъектТеплопотребления.Название CustomAttributes)

        // *** End programmer edit section *** (ОбъектТеплопотребления.Название CustomAttributes)
        [StrLen(255)]
        [NotNull()]
        public virtual string Название
        {
            get
            {
                // *** Start programmer edit section *** (ОбъектТеплопотребления.Название Get start)

                // *** End programmer edit section *** (ОбъектТеплопотребления.Название Get start)
                string result = this.fНазвание;
                // *** Start programmer edit section *** (ОбъектТеплопотребления.Название Get end)

                // *** End programmer edit section *** (ОбъектТеплопотребления.Название Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ОбъектТеплопотребления.Название Set start)

                // *** End programmer edit section *** (ОбъектТеплопотребления.Название Set start)
                this.fНазвание = value;
                // *** Start programmer edit section *** (ОбъектТеплопотребления.Название Set end)

                // *** End programmer edit section *** (ОбъектТеплопотребления.Название Set end)
            }
        }
        
        /// <summary>
        /// ДатаУстановки.
        /// </summary>
        // *** Start programmer edit section *** (ОбъектТеплопотребления.ДатаУстановки CustomAttributes)

        // *** End programmer edit section *** (ОбъектТеплопотребления.ДатаУстановки CustomAttributes)
        [NotNull()]
        public virtual System.DateTime ДатаУстановки
        {
            get
            {
                // *** Start programmer edit section *** (ОбъектТеплопотребления.ДатаУстановки Get start)

                // *** End programmer edit section *** (ОбъектТеплопотребления.ДатаУстановки Get start)
                System.DateTime result = this.fДатаУстановки;
                // *** Start programmer edit section *** (ОбъектТеплопотребления.ДатаУстановки Get end)

                // *** End programmer edit section *** (ОбъектТеплопотребления.ДатаУстановки Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ОбъектТеплопотребления.ДатаУстановки Set start)

                // *** End programmer edit section *** (ОбъектТеплопотребления.ДатаУстановки Set start)
                this.fДатаУстановки = value;
                // *** Start programmer edit section *** (ОбъектТеплопотребления.ДатаУстановки Set end)

                // *** End programmer edit section *** (ОбъектТеплопотребления.ДатаУстановки Set end)
            }
        }
        
        /// <summary>
        /// ЦБкод.
        /// </summary>
        // *** Start programmer edit section *** (ОбъектТеплопотребления.ЦБкод CustomAttributes)

        // *** End programmer edit section *** (ОбъектТеплопотребления.ЦБкод CustomAttributes)
        [StrLen(255)]
        public virtual string ЦБкод
        {
            get
            {
                // *** Start programmer edit section *** (ОбъектТеплопотребления.ЦБкод Get start)

                // *** End programmer edit section *** (ОбъектТеплопотребления.ЦБкод Get start)
                string result = this.fЦБкод;
                // *** Start programmer edit section *** (ОбъектТеплопотребления.ЦБкод Get end)

                // *** End programmer edit section *** (ОбъектТеплопотребления.ЦБкод Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ОбъектТеплопотребления.ЦБкод Set start)

                // *** End programmer edit section *** (ОбъектТеплопотребления.ЦБкод Set start)
                this.fЦБкод = value;
                // *** Start programmer edit section *** (ОбъектТеплопотребления.ЦБкод Set end)

                // *** End programmer edit section *** (ОбъектТеплопотребления.ЦБкод Set end)
            }
        }
        
        /// <summary>
        /// Площадь.
        /// </summary>
        // *** Start programmer edit section *** (ОбъектТеплопотребления.Площадь CustomAttributes)

        // *** End programmer edit section *** (ОбъектТеплопотребления.Площадь CustomAttributes)
        [NotNull()]
        public virtual double Площадь
        {
            get
            {
                // *** Start programmer edit section *** (ОбъектТеплопотребления.Площадь Get start)

                // *** End programmer edit section *** (ОбъектТеплопотребления.Площадь Get start)
                double result = this.fПлощадь;
                // *** Start programmer edit section *** (ОбъектТеплопотребления.Площадь Get end)

                // *** End programmer edit section *** (ОбъектТеплопотребления.Площадь Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ОбъектТеплопотребления.Площадь Set start)

                // *** End programmer edit section *** (ОбъектТеплопотребления.Площадь Set start)
                this.fПлощадь = value;
                // *** Start programmer edit section *** (ОбъектТеплопотребления.Площадь Set end)

                // *** End programmer edit section *** (ОбъектТеплопотребления.Площадь Set end)
            }
        }
        
        /// <summary>
        /// Объект теплопотребления.
        /// </summary>
        // *** Start programmer edit section *** (ОбъектТеплопотребления.Потребитель CustomAttributes)

        // *** End programmer edit section *** (ОбъектТеплопотребления.Потребитель CustomAttributes)
        [PropertyStorage(new string[] {
                "Потребитель"})]
        [NotNull()]
        public virtual IIS.ThermoObjectTask6.Потребитель Потребитель
        {
            get
            {
                // *** Start programmer edit section *** (ОбъектТеплопотребления.Потребитель Get start)

                // *** End programmer edit section *** (ОбъектТеплопотребления.Потребитель Get start)
                IIS.ThermoObjectTask6.Потребитель result = this.fПотребитель;
                // *** Start programmer edit section *** (ОбъектТеплопотребления.Потребитель Get end)

                // *** End programmer edit section *** (ОбъектТеплопотребления.Потребитель Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ОбъектТеплопотребления.Потребитель Set start)

                // *** End programmer edit section *** (ОбъектТеплопотребления.Потребитель Set start)
                this.fПотребитель = value;
                // *** Start programmer edit section *** (ОбъектТеплопотребления.Потребитель Set end)

                // *** End programmer edit section *** (ОбъектТеплопотребления.Потребитель Set end)
            }
        }
        
        /// <summary>
        /// Объект теплопотребления.
        /// </summary>
        // *** Start programmer edit section *** (ОбъектТеплопотребления.УчастокСети CustomAttributes)

        // *** End programmer edit section *** (ОбъектТеплопотребления.УчастокСети CustomAttributes)
        public virtual IIS.ThermoObjectTask6.DetailArrayOfУчастокСети УчастокСети
        {
            get
            {
                // *** Start programmer edit section *** (ОбъектТеплопотребления.УчастокСети Get start)

                // *** End programmer edit section *** (ОбъектТеплопотребления.УчастокСети Get start)
                if ((this.fУчастокСети == null))
                {
                    this.fУчастокСети = new IIS.ThermoObjectTask6.DetailArrayOfУчастокСети(this);
                }
                IIS.ThermoObjectTask6.DetailArrayOfУчастокСети result = this.fУчастокСети;
                // *** Start programmer edit section *** (ОбъектТеплопотребления.УчастокСети Get end)

                // *** End programmer edit section *** (ОбъектТеплопотребления.УчастокСети Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ОбъектТеплопотребления.УчастокСети Set start)

                // *** End programmer edit section *** (ОбъектТеплопотребления.УчастокСети Set start)
                this.fУчастокСети = value;
                // *** Start programmer edit section *** (ОбъектТеплопотребления.УчастокСети Set end)

                // *** End programmer edit section *** (ОбъектТеплопотребления.УчастокСети Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку IIS.ThermoObjectTask6.Здание.
        /// </summary>
        // *** Start programmer edit section *** (ОбъектТеплопотребления.Здание CustomAttributes)

        // *** End programmer edit section *** (ОбъектТеплопотребления.Здание CustomAttributes)
        [Agregator()]
        [NotNull()]
        [PropertyStorage(new string[] {
                "Здание"})]
        public virtual IIS.ThermoObjectTask6.Здание Здание
        {
            get
            {
                // *** Start programmer edit section *** (ОбъектТеплопотребления.Здание Get start)

                // *** End programmer edit section *** (ОбъектТеплопотребления.Здание Get start)
                IIS.ThermoObjectTask6.Здание result = this.fЗдание;
                // *** Start programmer edit section *** (ОбъектТеплопотребления.Здание Get end)

                // *** End programmer edit section *** (ОбъектТеплопотребления.Здание Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ОбъектТеплопотребления.Здание Set start)

                // *** End programmer edit section *** (ОбъектТеплопотребления.Здание Set start)
                this.fЗдание = value;
                // *** Start programmer edit section *** (ОбъектТеплопотребления.Здание Set end)

                // *** End programmer edit section *** (ОбъектТеплопотребления.Здание Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ОбъектТеплопотребленияE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ОбъектТеплопотребленияE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ОбъектТеплопотребленияE", typeof(IIS.ThermoObjectTask6.ОбъектТеплопотребления));
                }
            }
            
            /// <summary>
            /// "ОбъектТеплопотребленияL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ОбъектТеплопотребленияL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ОбъектТеплопотребленияL", typeof(IIS.ThermoObjectTask6.ОбъектТеплопотребления));
                }
            }
        }
    }
    
    /// <summary>
    /// Detail array of ОбъектТеплопотребления.
    /// </summary>
    // *** Start programmer edit section *** (DetailArrayDetailArrayOfОбъектТеплопотребления CustomAttributes)

    // *** End programmer edit section *** (DetailArrayDetailArrayOfОбъектТеплопотребления CustomAttributes)
    public class DetailArrayOfОбъектТеплопотребления : ICSSoft.STORMNET.DetailArray
    {
        
        // *** Start programmer edit section *** (IIS.ThermoObjectTask6.DetailArrayOfОбъектТеплопотребления members)

        // *** End programmer edit section *** (IIS.ThermoObjectTask6.DetailArrayOfОбъектТеплопотребления members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type ОбъектТеплопотребления by index.
        /// </summary>
        /// <summary>
        /// Adds object with type ОбъектТеплопотребления.
        /// </summary>
        public DetailArrayOfОбъектТеплопотребления(IIS.ThermoObjectTask6.Здание fЗдание) : 
                base(typeof(ОбъектТеплопотребления), ((ICSSoft.STORMNET.DataObject)(fЗдание)))
        {
        }
        
        public IIS.ThermoObjectTask6.ОбъектТеплопотребления this[int index]
        {
            get
            {
                return ((IIS.ThermoObjectTask6.ОбъектТеплопотребления)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(IIS.ThermoObjectTask6.ОбъектТеплопотребления dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
