//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.ThermoObjectTask6
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Сетевой район.
    /// </summary>
    // *** Start programmer edit section *** (СетевойРайон CustomAttributes)

    // *** End programmer edit section *** (СетевойРайон CustomAttributes)
    [AutoAltered()]
    [Caption("Сетевой район")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("СетевойРайонE", new string[] {
            "Название as \'Название\'"})]
    [View("СетевойРайонL", new string[] {
            "Название as \'Название\'"})]
    public class СетевойРайон : ICSSoft.STORMNET.DataObject
    {
        
        private string fНазвание;
        
        // *** Start programmer edit section *** (СетевойРайон CustomMembers)

        // *** End programmer edit section *** (СетевойРайон CustomMembers)

        
        /// <summary>
        /// Название.
        /// </summary>
        // *** Start programmer edit section *** (СетевойРайон.Название CustomAttributes)

        // *** End programmer edit section *** (СетевойРайон.Название CustomAttributes)
        [StrLen(255)]
        public virtual string Название
        {
            get
            {
                // *** Start programmer edit section *** (СетевойРайон.Название Get start)

                // *** End programmer edit section *** (СетевойРайон.Название Get start)
                string result = this.fНазвание;
                // *** Start programmer edit section *** (СетевойРайон.Название Get end)

                // *** End programmer edit section *** (СетевойРайон.Название Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (СетевойРайон.Название Set start)

                // *** End programmer edit section *** (СетевойРайон.Название Set start)
                this.fНазвание = value;
                // *** Start programmer edit section *** (СетевойРайон.Название Set end)

                // *** End programmer edit section *** (СетевойРайон.Название Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "СетевойРайонE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View СетевойРайонE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("СетевойРайонE", typeof(IIS.ThermoObjectTask6.СетевойРайон));
                }
            }
            
            /// <summary>
            /// "СетевойРайонL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View СетевойРайонL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("СетевойРайонL", typeof(IIS.ThermoObjectTask6.СетевойРайон));
                }
            }
        }
    }
}
