//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.ThermoObjectTask6
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Участок сети.
    /// </summary>
    // *** Start programmer edit section *** (УчастокСети CustomAttributes)

    // *** End programmer edit section *** (УчастокСети CustomAttributes)
    [AutoAltered()]
    [Caption("Участок сети")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("УчастокСетиE", new string[] {
            "Номер as \'Номер\'",
            "ТипИзоляции as \'Тип изоляции\'",
            "ТипПрокладки as \'Тип прокладки\'",
            "ДатаПрокладки as \'Дата прокладки\'",
            "ИнфоОбУчасткеСети as \'Инфо об участке сети\'"})]
    public class УчастокСети : ICSSoft.STORMNET.DataObject
    {
        
        private int fНомер;
        
        private IIS.ThermoObjectTask6.ТипыИзоляции fТипИзоляции;
        
        private IIS.ThermoObjectTask6.ТипыПрокладки fТипПрокладки;
        
        private System.DateTime fДатаПрокладки;
        
        private IIS.ThermoObjectTask6.ОбъектТеплопотребления fОбъектТеплопотребления;
        
        // *** Start programmer edit section *** (УчастокСети CustomMembers)

        // *** End programmer edit section *** (УчастокСети CustomMembers)

        
        /// <summary>
        /// Номер.
        /// </summary>
        // *** Start programmer edit section *** (УчастокСети.Номер CustomAttributes)

        // *** End programmer edit section *** (УчастокСети.Номер CustomAttributes)
        [NotNull()]
        public virtual int Номер
        {
            get
            {
                // *** Start programmer edit section *** (УчастокСети.Номер Get start)

                // *** End programmer edit section *** (УчастокСети.Номер Get start)
                int result = this.fНомер;
                // *** Start programmer edit section *** (УчастокСети.Номер Get end)

                // *** End programmer edit section *** (УчастокСети.Номер Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (УчастокСети.Номер Set start)

                // *** End programmer edit section *** (УчастокСети.Номер Set start)
                this.fНомер = value;
                // *** Start programmer edit section *** (УчастокСети.Номер Set end)

                // *** End programmer edit section *** (УчастокСети.Номер Set end)
            }
        }
        
        /// <summary>
        /// ТипИзоляции.
        /// </summary>
        // *** Start programmer edit section *** (УчастокСети.ТипИзоляции CustomAttributes)

        // *** End programmer edit section *** (УчастокСети.ТипИзоляции CustomAttributes)
        public virtual IIS.ThermoObjectTask6.ТипыИзоляции ТипИзоляции
        {
            get
            {
                // *** Start programmer edit section *** (УчастокСети.ТипИзоляции Get start)

                // *** End programmer edit section *** (УчастокСети.ТипИзоляции Get start)
                IIS.ThermoObjectTask6.ТипыИзоляции result = this.fТипИзоляции;
                // *** Start programmer edit section *** (УчастокСети.ТипИзоляции Get end)

                // *** End programmer edit section *** (УчастокСети.ТипИзоляции Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (УчастокСети.ТипИзоляции Set start)

                // *** End programmer edit section *** (УчастокСети.ТипИзоляции Set start)
                this.fТипИзоляции = value;
                // *** Start programmer edit section *** (УчастокСети.ТипИзоляции Set end)

                // *** End programmer edit section *** (УчастокСети.ТипИзоляции Set end)
            }
        }
        
        /// <summary>
        /// ТипПрокладки.
        /// </summary>
        // *** Start programmer edit section *** (УчастокСети.ТипПрокладки CustomAttributes)

        // *** End programmer edit section *** (УчастокСети.ТипПрокладки CustomAttributes)
        public virtual IIS.ThermoObjectTask6.ТипыПрокладки ТипПрокладки
        {
            get
            {
                // *** Start programmer edit section *** (УчастокСети.ТипПрокладки Get start)

                // *** End programmer edit section *** (УчастокСети.ТипПрокладки Get start)
                IIS.ThermoObjectTask6.ТипыПрокладки result = this.fТипПрокладки;
                // *** Start programmer edit section *** (УчастокСети.ТипПрокладки Get end)

                // *** End programmer edit section *** (УчастокСети.ТипПрокладки Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (УчастокСети.ТипПрокладки Set start)

                // *** End programmer edit section *** (УчастокСети.ТипПрокладки Set start)
                this.fТипПрокладки = value;
                // *** Start programmer edit section *** (УчастокСети.ТипПрокладки Set end)

                // *** End programmer edit section *** (УчастокСети.ТипПрокладки Set end)
            }
        }
        
        /// <summary>
        /// ДатаПрокладки.
        /// </summary>
        // *** Start programmer edit section *** (УчастокСети.ДатаПрокладки CustomAttributes)

        // *** End programmer edit section *** (УчастокСети.ДатаПрокладки CustomAttributes)
        [NotNull()]
        public virtual System.DateTime ДатаПрокладки
        {
            get
            {
                // *** Start programmer edit section *** (УчастокСети.ДатаПрокладки Get start)

                // *** End programmer edit section *** (УчастокСети.ДатаПрокладки Get start)
                System.DateTime result = this.fДатаПрокладки;
                // *** Start programmer edit section *** (УчастокСети.ДатаПрокладки Get end)

                // *** End programmer edit section *** (УчастокСети.ДатаПрокладки Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (УчастокСети.ДатаПрокладки Set start)

                // *** End programmer edit section *** (УчастокСети.ДатаПрокладки Set start)
                this.fДатаПрокладки = value;
                // *** Start programmer edit section *** (УчастокСети.ДатаПрокладки Set end)

                // *** End programmer edit section *** (УчастокСети.ДатаПрокладки Set end)
            }
        }
        
        /// <summary>
        /// ИнфоОбУчасткеСети.
        /// </summary>
        // *** Start programmer edit section *** (УчастокСети.ИнфоОбУчасткеСети CustomAttributes)

        // *** End programmer edit section *** (УчастокСети.ИнфоОбУчасткеСети CustomAttributes)
        [ICSSoft.STORMNET.NotStored()]
        [StrLen(255)]
        public virtual string ИнфоОбУчасткеСети
        {
            get
            {
                // *** Start programmer edit section *** (УчастокСети.ИнфоОбУчасткеСети Get)
                TODO: //При добавлении нового участка сети вызывает исключение, т.к. пытается получить объект this до его создания
                //string info = "Адрес: " + this.ОбъектТеплопотребления.Здание.Адрес + "; Название ОТ: " + this.ОбъектТеплопотребления.Название + "; Номер: " + this.Номер + "; Тип изоляции: " + this.ТипИзоляции + ";";
                //return info;
                return null;
                // *** End programmer edit section *** (УчастокСети.ИнфоОбУчасткеСети Get)
            }
            set
            {
                // *** Start programmer edit section *** (УчастокСети.ИнфоОбУчасткеСети Set)

                // *** End programmer edit section *** (УчастокСети.ИнфоОбУчасткеСети Set)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку IIS.ThermoObjectTask6.ОбъектТеплопотребления.
        /// </summary>
        // *** Start programmer edit section *** (УчастокСети.ОбъектТеплопотребления CustomAttributes)

        // *** End programmer edit section *** (УчастокСети.ОбъектТеплопотребления CustomAttributes)
        [Agregator()]
        [NotNull()]
        [PropertyStorage(new string[] {
                "ОбъектТеплопотребления"})]
        public virtual IIS.ThermoObjectTask6.ОбъектТеплопотребления ОбъектТеплопотребления
        {
            get
            {
                // *** Start programmer edit section *** (УчастокСети.ОбъектТеплопотребления Get start)

                // *** End programmer edit section *** (УчастокСети.ОбъектТеплопотребления Get start)
                IIS.ThermoObjectTask6.ОбъектТеплопотребления result = this.fОбъектТеплопотребления;
                // *** Start programmer edit section *** (УчастокСети.ОбъектТеплопотребления Get end)

                // *** End programmer edit section *** (УчастокСети.ОбъектТеплопотребления Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (УчастокСети.ОбъектТеплопотребления Set start)

                // *** End programmer edit section *** (УчастокСети.ОбъектТеплопотребления Set start)
                this.fОбъектТеплопотребления = value;
                // *** Start programmer edit section *** (УчастокСети.ОбъектТеплопотребления Set end)

                // *** End programmer edit section *** (УчастокСети.ОбъектТеплопотребления Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "УчастокСетиE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View УчастокСетиE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("УчастокСетиE", typeof(IIS.ThermoObjectTask6.УчастокСети));
                }
            }
        }
    }
    
    /// <summary>
    /// Detail array of УчастокСети.
    /// </summary>
    // *** Start programmer edit section *** (DetailArrayDetailArrayOfУчастокСети CustomAttributes)

    // *** End programmer edit section *** (DetailArrayDetailArrayOfУчастокСети CustomAttributes)
    public class DetailArrayOfУчастокСети : ICSSoft.STORMNET.DetailArray
    {
        
        // *** Start programmer edit section *** (IIS.ThermoObjectTask6.DetailArrayOfУчастокСети members)

        // *** End programmer edit section *** (IIS.ThermoObjectTask6.DetailArrayOfУчастокСети members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type УчастокСети by index.
        /// </summary>
        /// <summary>
        /// Adds object with type УчастокСети.
        /// </summary>
        public DetailArrayOfУчастокСети(IIS.ThermoObjectTask6.ОбъектТеплопотребления fОбъектТеплопотребления) : 
                base(typeof(УчастокСети), ((ICSSoft.STORMNET.DataObject)(fОбъектТеплопотребления)))
        {
        }
        
        public IIS.ThermoObjectTask6.УчастокСети this[int index]
        {
            get
            {
                return ((IIS.ThermoObjectTask6.УчастокСети)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(IIS.ThermoObjectTask6.УчастокСети dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
