//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Task6
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET.Business;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// ОбъектТеплопотребления.
    /// </summary>
    // *** Start programmer edit section *** (ОбъектТеплопотребления CustomAttributes)

    // *** End programmer edit section *** (ОбъектТеплопотребления CustomAttributes)
    [BusinessServer("IIS.Task6.ЦБкодДублиУСплощадиОТ, Task6.BusinessServers", ICSSoft.STORMNET.Business.DataServiceObjectEvents.OnAllEvents)]
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    public class ОбъектТеплопотребления : ICSSoft.STORMNET.DataObject
    {
        
        private string fНазвание;
        
        private System.DateTime fДатаУстановки;
        
        private string fТипОТ;
        
        private int fТепловаяНагрузка;
        
        private string fЦБкод;
        
        private double fПлощадь;
        
        private IIS.Task6.Потребитель fПотребитель;
        
        private IIS.Task6.DetailArrayOfУчастокСети fУчастокСети;
        
        private IIS.Task6.Здание fЗдание;
        
        // *** Start programmer edit section *** (ОбъектТеплопотребления CustomMembers)

        // *** End programmer edit section *** (ОбъектТеплопотребления CustomMembers)

        
        /// <summary>
        /// Название.
        /// </summary>
        // *** Start programmer edit section *** (ОбъектТеплопотребления.Название CustomAttributes)

        // *** End programmer edit section *** (ОбъектТеплопотребления.Название CustomAttributes)
        [StrLen(255)]
        public virtual string Название
        {
            get
            {
                // *** Start programmer edit section *** (ОбъектТеплопотребления.Название Get start)

                // *** End programmer edit section *** (ОбъектТеплопотребления.Название Get start)
                string result = this.fНазвание;
                // *** Start programmer edit section *** (ОбъектТеплопотребления.Название Get end)

                // *** End programmer edit section *** (ОбъектТеплопотребления.Название Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ОбъектТеплопотребления.Название Set start)

                // *** End programmer edit section *** (ОбъектТеплопотребления.Название Set start)
                this.fНазвание = value;
                // *** Start programmer edit section *** (ОбъектТеплопотребления.Название Set end)

                // *** End programmer edit section *** (ОбъектТеплопотребления.Название Set end)
            }
        }
        
        /// <summary>
        /// ДатаУстановки.
        /// </summary>
        // *** Start programmer edit section *** (ОбъектТеплопотребления.ДатаУстановки CustomAttributes)

        // *** End programmer edit section *** (ОбъектТеплопотребления.ДатаУстановки CustomAttributes)
        public virtual System.DateTime ДатаУстановки
        {
            get
            {
                // *** Start programmer edit section *** (ОбъектТеплопотребления.ДатаУстановки Get start)

                // *** End programmer edit section *** (ОбъектТеплопотребления.ДатаУстановки Get start)
                System.DateTime result = this.fДатаУстановки;
                // *** Start programmer edit section *** (ОбъектТеплопотребления.ДатаУстановки Get end)

                // *** End programmer edit section *** (ОбъектТеплопотребления.ДатаУстановки Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ОбъектТеплопотребления.ДатаУстановки Set start)

                // *** End programmer edit section *** (ОбъектТеплопотребления.ДатаУстановки Set start)
                this.fДатаУстановки = value;
                // *** Start programmer edit section *** (ОбъектТеплопотребления.ДатаУстановки Set end)

                // *** End programmer edit section *** (ОбъектТеплопотребления.ДатаУстановки Set end)
            }
        }
        
        /// <summary>
        /// ТипОТ.
        /// </summary>
        // *** Start programmer edit section *** (ОбъектТеплопотребления.ТипОТ CustomAttributes)

        // *** End programmer edit section *** (ОбъектТеплопотребления.ТипОТ CustomAttributes)
        [StrLen(255)]
        public virtual string ТипОТ
        {
            get
            {
                // *** Start programmer edit section *** (ОбъектТеплопотребления.ТипОТ Get start)

                // *** End programmer edit section *** (ОбъектТеплопотребления.ТипОТ Get start)
                string result = this.fТипОТ;
                // *** Start programmer edit section *** (ОбъектТеплопотребления.ТипОТ Get end)

                // *** End programmer edit section *** (ОбъектТеплопотребления.ТипОТ Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ОбъектТеплопотребления.ТипОТ Set start)

                // *** End programmer edit section *** (ОбъектТеплопотребления.ТипОТ Set start)
                this.fТипОТ = value;
                // *** Start programmer edit section *** (ОбъектТеплопотребления.ТипОТ Set end)

                // *** End programmer edit section *** (ОбъектТеплопотребления.ТипОТ Set end)
            }
        }
        
        /// <summary>
        /// ТепловаяНагрузка.
        /// </summary>
        // *** Start programmer edit section *** (ОбъектТеплопотребления.ТепловаяНагрузка CustomAttributes)

        // *** End programmer edit section *** (ОбъектТеплопотребления.ТепловаяНагрузка CustomAttributes)
        public virtual int ТепловаяНагрузка
        {
            get
            {
                // *** Start programmer edit section *** (ОбъектТеплопотребления.ТепловаяНагрузка Get start)

                // *** End programmer edit section *** (ОбъектТеплопотребления.ТепловаяНагрузка Get start)
                int result = this.fТепловаяНагрузка;
                // *** Start programmer edit section *** (ОбъектТеплопотребления.ТепловаяНагрузка Get end)

                // *** End programmer edit section *** (ОбъектТеплопотребления.ТепловаяНагрузка Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ОбъектТеплопотребления.ТепловаяНагрузка Set start)

                // *** End programmer edit section *** (ОбъектТеплопотребления.ТепловаяНагрузка Set start)
                this.fТепловаяНагрузка = value;
                // *** Start programmer edit section *** (ОбъектТеплопотребления.ТепловаяНагрузка Set end)

                // *** End programmer edit section *** (ОбъектТеплопотребления.ТепловаяНагрузка Set end)
            }
        }
        
        /// <summary>
        /// ЦБкод.
        /// </summary>
        // *** Start programmer edit section *** (ОбъектТеплопотребления.ЦБкод CustomAttributes)

        // *** End programmer edit section *** (ОбъектТеплопотребления.ЦБкод CustomAttributes)
        [StrLen(255)]
        public virtual string ЦБкод
        {
            get
            {
                // *** Start programmer edit section *** (ОбъектТеплопотребления.ЦБкод Get start)

                // *** End programmer edit section *** (ОбъектТеплопотребления.ЦБкод Get start)
                string result = this.fЦБкод;
                // *** Start programmer edit section *** (ОбъектТеплопотребления.ЦБкод Get end)

                // *** End programmer edit section *** (ОбъектТеплопотребления.ЦБкод Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ОбъектТеплопотребления.ЦБкод Set start)

                // *** End programmer edit section *** (ОбъектТеплопотребления.ЦБкод Set start)
                this.fЦБкод = value;
                // *** Start programmer edit section *** (ОбъектТеплопотребления.ЦБкод Set end)

                // *** End programmer edit section *** (ОбъектТеплопотребления.ЦБкод Set end)
            }
        }
        
        /// <summary>
        /// Площадь.
        /// </summary>
        // *** Start programmer edit section *** (ОбъектТеплопотребления.Площадь CustomAttributes)

        // *** End programmer edit section *** (ОбъектТеплопотребления.Площадь CustomAttributes)
        public virtual double Площадь
        {
            get
            {
                // *** Start programmer edit section *** (ОбъектТеплопотребления.Площадь Get start)

                // *** End programmer edit section *** (ОбъектТеплопотребления.Площадь Get start)
                double result = this.fПлощадь;
                // *** Start programmer edit section *** (ОбъектТеплопотребления.Площадь Get end)

                // *** End programmer edit section *** (ОбъектТеплопотребления.Площадь Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ОбъектТеплопотребления.Площадь Set start)

                // *** End programmer edit section *** (ОбъектТеплопотребления.Площадь Set start)
                this.fПлощадь = value;
                // *** Start programmer edit section *** (ОбъектТеплопотребления.Площадь Set end)

                // *** End programmer edit section *** (ОбъектТеплопотребления.Площадь Set end)
            }
        }
        
        /// <summary>
        /// ОбъектТеплопотребления.
        /// </summary>
        // *** Start programmer edit section *** (ОбъектТеплопотребления.Потребитель CustomAttributes)

        // *** End programmer edit section *** (ОбъектТеплопотребления.Потребитель CustomAttributes)
        [PropertyStorage(new string[] {
                "Потребитель"})]
        [NotNull()]
        public virtual IIS.Task6.Потребитель Потребитель
        {
            get
            {
                // *** Start programmer edit section *** (ОбъектТеплопотребления.Потребитель Get start)

                // *** End programmer edit section *** (ОбъектТеплопотребления.Потребитель Get start)
                IIS.Task6.Потребитель result = this.fПотребитель;
                // *** Start programmer edit section *** (ОбъектТеплопотребления.Потребитель Get end)

                // *** End programmer edit section *** (ОбъектТеплопотребления.Потребитель Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ОбъектТеплопотребления.Потребитель Set start)

                // *** End programmer edit section *** (ОбъектТеплопотребления.Потребитель Set start)
                this.fПотребитель = value;
                // *** Start programmer edit section *** (ОбъектТеплопотребления.Потребитель Set end)

                // *** End programmer edit section *** (ОбъектТеплопотребления.Потребитель Set end)
            }
        }
        
        /// <summary>
        /// ОбъектТеплопотребления.
        /// </summary>
        // *** Start programmer edit section *** (ОбъектТеплопотребления.УчастокСети CustomAttributes)

        // *** End programmer edit section *** (ОбъектТеплопотребления.УчастокСети CustomAttributes)
        public virtual IIS.Task6.DetailArrayOfУчастокСети УчастокСети
        {
            get
            {
                // *** Start programmer edit section *** (ОбъектТеплопотребления.УчастокСети Get start)

                // *** End programmer edit section *** (ОбъектТеплопотребления.УчастокСети Get start)
                if ((this.fУчастокСети == null))
                {
                    this.fУчастокСети = new IIS.Task6.DetailArrayOfУчастокСети(this);
                }
                IIS.Task6.DetailArrayOfУчастокСети result = this.fУчастокСети;
                // *** Start programmer edit section *** (ОбъектТеплопотребления.УчастокСети Get end)

                // *** End programmer edit section *** (ОбъектТеплопотребления.УчастокСети Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ОбъектТеплопотребления.УчастокСети Set start)

                // *** End programmer edit section *** (ОбъектТеплопотребления.УчастокСети Set start)
                this.fУчастокСети = value;
                // *** Start programmer edit section *** (ОбъектТеплопотребления.УчастокСети Set end)

                // *** End programmer edit section *** (ОбъектТеплопотребления.УчастокСети Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку IIS.Task6.Здание.
        /// </summary>
        // *** Start programmer edit section *** (ОбъектТеплопотребления.Здание CustomAttributes)

        // *** End programmer edit section *** (ОбъектТеплопотребления.Здание CustomAttributes)
        [Agregator()]
        [NotNull()]
        [PropertyStorage(new string[] {
                "Здание"})]
        public virtual IIS.Task6.Здание Здание
        {
            get
            {
                // *** Start programmer edit section *** (ОбъектТеплопотребления.Здание Get start)

                // *** End programmer edit section *** (ОбъектТеплопотребления.Здание Get start)
                IIS.Task6.Здание result = this.fЗдание;
                // *** Start programmer edit section *** (ОбъектТеплопотребления.Здание Get end)

                // *** End programmer edit section *** (ОбъектТеплопотребления.Здание Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ОбъектТеплопотребления.Здание Set start)

                // *** End programmer edit section *** (ОбъектТеплопотребления.Здание Set start)
                this.fЗдание = value;
                // *** Start programmer edit section *** (ОбъектТеплопотребления.Здание Set end)

                // *** End programmer edit section *** (ОбъектТеплопотребления.Здание Set end)
            }
        }
    }
    
    /// <summary>
    /// Detail array of ОбъектТеплопотребления.
    /// </summary>
    // *** Start programmer edit section *** (DetailArrayDetailArrayOfОбъектТеплопотребления CustomAttributes)

    // *** End programmer edit section *** (DetailArrayDetailArrayOfОбъектТеплопотребления CustomAttributes)
    public class DetailArrayOfОбъектТеплопотребления : ICSSoft.STORMNET.DetailArray
    {
        
        // *** Start programmer edit section *** (IIS.Task6.DetailArrayOfОбъектТеплопотребления members)

        // *** End programmer edit section *** (IIS.Task6.DetailArrayOfОбъектТеплопотребления members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type ОбъектТеплопотребления by index.
        /// </summary>
        /// <summary>
        /// Adds object with type ОбъектТеплопотребления.
        /// </summary>
        public DetailArrayOfОбъектТеплопотребления(IIS.Task6.Здание fЗдание) : 
                base(typeof(ОбъектТеплопотребления), ((ICSSoft.STORMNET.DataObject)(fЗдание)))
        {
        }
        
        public IIS.Task6.ОбъектТеплопотребления this[int index]
        {
            get
            {
                return ((IIS.Task6.ОбъектТеплопотребления)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(IIS.Task6.ОбъектТеплопотребления dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
