//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Task6
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// ТипыИзоляции.
    /// </summary>
    // *** Start programmer edit section *** (ТипыИзоляции CustomAttributes)

    // *** End programmer edit section *** (ТипыИзоляции CustomAttributes)
    public enum ТипыИзоляции
    {
        
        /// <summary>
        /// 
        /// </summary>
        // *** Start programmer edit section *** (ТипыИзоляции.Пенополиуретан CustomAttributes)

        // *** End programmer edit section *** (ТипыИзоляции.Пенополиуретан CustomAttributes)
        Пенополиуретан,
        
        /// <summary>
        /// 
        /// </summary>
        // *** Start programmer edit section *** (ТипыИзоляции.ПенополимерМинерал CustomAttributes)

        // *** End programmer edit section *** (ТипыИзоляции.ПенополимерМинерал CustomAttributes)
        [Caption("Пенополимер-минерал")]
        ПенополимерМинерал,
        
        /// <summary>
        /// 
        /// </summary>
        // *** Start programmer edit section *** (ТипыИзоляции.Армапенобетон CustomAttributes)

        // *** End programmer edit section *** (ТипыИзоляции.Армапенобетон CustomAttributes)
        Армапенобетон,
    }
}
