//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Task6
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// УчастокСети.
    /// </summary>
    // *** Start programmer edit section *** (УчастокСети CustomAttributes)

    // *** End programmer edit section *** (УчастокСети CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    public class УчастокСети : ICSSoft.STORMNET.DataObject
    {
        
        private int fНомер;
        
        private string fТипИзоляции;
        
        private string fТипПрокладки;
        
        private int fГодПрокладки;
        
        private IIS.Task6.ОбъектТеплопотребления fОбъектТеплопотребления;
        
        // *** Start programmer edit section *** (УчастокСети CustomMembers)

        // *** End programmer edit section *** (УчастокСети CustomMembers)

        
        /// <summary>
        /// Номер.
        /// </summary>
        // *** Start programmer edit section *** (УчастокСети.Номер CustomAttributes)

        // *** End programmer edit section *** (УчастокСети.Номер CustomAttributes)
        public virtual int Номер
        {
            get
            {
                // *** Start programmer edit section *** (УчастокСети.Номер Get start)

                // *** End programmer edit section *** (УчастокСети.Номер Get start)
                int result = this.fНомер;
                // *** Start programmer edit section *** (УчастокСети.Номер Get end)

                // *** End programmer edit section *** (УчастокСети.Номер Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (УчастокСети.Номер Set start)

                // *** End programmer edit section *** (УчастокСети.Номер Set start)
                this.fНомер = value;
                // *** Start programmer edit section *** (УчастокСети.Номер Set end)

                // *** End programmer edit section *** (УчастокСети.Номер Set end)
            }
        }
        
        /// <summary>
        /// ТипИзоляции.
        /// </summary>
        // *** Start programmer edit section *** (УчастокСети.ТипИзоляции CustomAttributes)

        // *** End programmer edit section *** (УчастокСети.ТипИзоляции CustomAttributes)
        [StrLen(255)]
        public virtual string ТипИзоляции
        {
            get
            {
                // *** Start programmer edit section *** (УчастокСети.ТипИзоляции Get start)

                // *** End programmer edit section *** (УчастокСети.ТипИзоляции Get start)
                string result = this.fТипИзоляции;
                // *** Start programmer edit section *** (УчастокСети.ТипИзоляции Get end)

                // *** End programmer edit section *** (УчастокСети.ТипИзоляции Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (УчастокСети.ТипИзоляции Set start)

                // *** End programmer edit section *** (УчастокСети.ТипИзоляции Set start)
                this.fТипИзоляции = value;
                // *** Start programmer edit section *** (УчастокСети.ТипИзоляции Set end)

                // *** End programmer edit section *** (УчастокСети.ТипИзоляции Set end)
            }
        }
        
        /// <summary>
        /// ТипПрокладки.
        /// </summary>
        // *** Start programmer edit section *** (УчастокСети.ТипПрокладки CustomAttributes)

        // *** End programmer edit section *** (УчастокСети.ТипПрокладки CustomAttributes)
        [StrLen(255)]
        public virtual string ТипПрокладки
        {
            get
            {
                // *** Start programmer edit section *** (УчастокСети.ТипПрокладки Get start)

                // *** End programmer edit section *** (УчастокСети.ТипПрокладки Get start)
                string result = this.fТипПрокладки;
                // *** Start programmer edit section *** (УчастокСети.ТипПрокладки Get end)

                // *** End programmer edit section *** (УчастокСети.ТипПрокладки Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (УчастокСети.ТипПрокладки Set start)

                // *** End programmer edit section *** (УчастокСети.ТипПрокладки Set start)
                this.fТипПрокладки = value;
                // *** Start programmer edit section *** (УчастокСети.ТипПрокладки Set end)

                // *** End programmer edit section *** (УчастокСети.ТипПрокладки Set end)
            }
        }
        
        /// <summary>
        /// ГодПрокладки.
        /// </summary>
        // *** Start programmer edit section *** (УчастокСети.ГодПрокладки CustomAttributes)

        // *** End programmer edit section *** (УчастокСети.ГодПрокладки CustomAttributes)
        public virtual int ГодПрокладки
        {
            get
            {
                // *** Start programmer edit section *** (УчастокСети.ГодПрокладки Get start)

                // *** End programmer edit section *** (УчастокСети.ГодПрокладки Get start)
                int result = this.fГодПрокладки;
                // *** Start programmer edit section *** (УчастокСети.ГодПрокладки Get end)

                // *** End programmer edit section *** (УчастокСети.ГодПрокладки Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (УчастокСети.ГодПрокладки Set start)

                // *** End programmer edit section *** (УчастокСети.ГодПрокладки Set start)
                this.fГодПрокладки = value;
                // *** Start programmer edit section *** (УчастокСети.ГодПрокладки Set end)

                // *** End programmer edit section *** (УчастокСети.ГодПрокладки Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку IIS.Task6.ОбъектТеплопотребления.
        /// </summary>
        // *** Start programmer edit section *** (УчастокСети.ОбъектТеплопотребления CustomAttributes)

        // *** End programmer edit section *** (УчастокСети.ОбъектТеплопотребления CustomAttributes)
        [Agregator()]
        [NotNull()]
        [PropertyStorage(new string[] {
                "ОбъектТеплопотребления"})]
        public virtual IIS.Task6.ОбъектТеплопотребления ОбъектТеплопотребления
        {
            get
            {
                // *** Start programmer edit section *** (УчастокСети.ОбъектТеплопотребления Get start)

                // *** End programmer edit section *** (УчастокСети.ОбъектТеплопотребления Get start)
                IIS.Task6.ОбъектТеплопотребления result = this.fОбъектТеплопотребления;
                // *** Start programmer edit section *** (УчастокСети.ОбъектТеплопотребления Get end)

                // *** End programmer edit section *** (УчастокСети.ОбъектТеплопотребления Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (УчастокСети.ОбъектТеплопотребления Set start)

                // *** End programmer edit section *** (УчастокСети.ОбъектТеплопотребления Set start)
                this.fОбъектТеплопотребления = value;
                // *** Start programmer edit section *** (УчастокСети.ОбъектТеплопотребления Set end)

                // *** End programmer edit section *** (УчастокСети.ОбъектТеплопотребления Set end)
            }
        }
    }
    
    /// <summary>
    /// Detail array of УчастокСети.
    /// </summary>
    // *** Start programmer edit section *** (DetailArrayDetailArrayOfУчастокСети CustomAttributes)

    // *** End programmer edit section *** (DetailArrayDetailArrayOfУчастокСети CustomAttributes)
    public class DetailArrayOfУчастокСети : ICSSoft.STORMNET.DetailArray
    {
        
        // *** Start programmer edit section *** (IIS.Task6.DetailArrayOfУчастокСети members)

        // *** End programmer edit section *** (IIS.Task6.DetailArrayOfУчастокСети members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type УчастокСети by index.
        /// </summary>
        /// <summary>
        /// Adds object with type УчастокСети.
        /// </summary>
        public DetailArrayOfУчастокСети(IIS.Task6.ОбъектТеплопотребления fОбъектТеплопотребления) : 
                base(typeof(УчастокСети), ((ICSSoft.STORMNET.DataObject)(fОбъектТеплопотребления)))
        {
        }
        
        public IIS.Task6.УчастокСети this[int index]
        {
            get
            {
                return ((IIS.Task6.УчастокСети)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(IIS.Task6.УчастокСети dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
