//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.ThermoObjectTask6
{
    using System;
    using System.Xml;


    // *** Start programmer edit section *** (Using statements)
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;


    using ICSSoft.STORMNET;
    using ICSSoft.STORMNET.FunctionalLanguage;
    using ICSSoft.STORMNET.FunctionalLanguage.SQLWhere;

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// ЦБкодДублиУСплощадиОТ.
    /// </summary>
    // *** Start programmer edit section *** (ЦБкодДублиУСплощадиОТ CustomAttributes)

    // *** End programmer edit section *** (ЦБкодДублиУСплощадиОТ CustomAttributes)
    [ICSSoft.STORMNET.AccessType(ICSSoft.STORMNET.AccessType.none)]
    public class ОбъектыТеплопотребленияBS : ICSSoft.STORMNET.Business.BusinessServer
    {

        // *** Start programmer edit section *** (ЦБкодДублиУСплощадиОТ CustomMembers)

        // *** End programmer edit section *** (ЦБкодДублиУСплощадиОТ CustomMembers)


        // *** Start programmer edit section *** (OnUpdateОбъектТеплопотребления CustomAttributes)

        // *** End programmer edit section *** (OnUpdateОбъектТеплопотребления CustomAttributes)
        public virtual ICSSoft.STORMNET.DataObject[] OnUpdateЗдание(IIS.ThermoObjectTask6.Здание UpdatedObject)
        {
            var ThermoObjectsInBuilding = UpdatedObject.ОбъектТеплопотребления.Cast<ОбъектТеплопотребления>();
            UpdatedObject.ПлощадьВсехОТ = 0;

            foreach (ОбъектТеплопотребления z in ThermoObjectsInBuilding)
            {
                UpdatedObject.ПлощадьВсехОТ += z.Площадь;
            }
            return new ICSSoft.STORMNET.DataObject[0];
        }

        public virtual ICSSoft.STORMNET.DataObject[] OnUpdateОбъектТеплопотребления(IIS.ThermoObjectTask6.ОбъектТеплопотребления UpdatedObject)
        {
            // *** Start programmer edit section *** (OnUpdateОбъектТеплопотребления)

            //Генерируем цифро-буквенный код для объекта теплопотребления
            string QRcode = CreateCode.FirstCreateCode.GenerateCode(UpdatedObject.Название, UpdatedObject.ДатаУстановки, UpdatedObject.Потребитель.ЛицевойСчёт);
            UpdatedObject.ЦБкод = QRcode;

            //Проверка на дублирование участков сети

            string DuplicateNetworksError = string.Empty;
            bool IsDuplicatedNetwork = false;

            var Networks = UpdatedObject.УчастокСети.Cast<УчастокСети>().Where(x=>x.GetStatus() != ObjectStatus.Deleted).OrderBy(x => x.Номер);

            Dictionary<int, ТипыПрокладки> NumbersAndTypesOfIsolation = new Dictionary<int, ТипыПрокладки>();
            foreach (УчастокСети z in Networks)
            {
                if (NumbersAndTypesOfIsolation.ContainsKey(z.Номер))
                {
                    if (NumbersAndTypesOfIsolation.ContainsValue(z.ТипПрокладки))
                    {
                        throw new Exception("Обнаружены дубли участков сети");
                        IsDuplicatedNetwork = true;
                    }
                }
                else NumbersAndTypesOfIsolation.Add(z.Номер, z.ТипПрокладки);
            }

            //Перевычисление площадей объектов теплопотребления в здании
            TODO: //При обращении к массиву объектов теплопотребления конкретного здания выдаёт количество объектов - 0
            UpdatedObject.Здание.ПлощадьВсехОТ = 0;
            for (int i = 0; i < UpdatedObject.Здание.ОбъектТеплопотребления.Count; i++)
            {
                UpdatedObject.Здание.ПлощадьВсехОТ += UpdatedObject.Здание.ОбъектТеплопотребления[i].Площадь;
            }

            //Обновление информации о каждом участке сети в не хранимом поле
            var участки = UpdatedObject.УчастокСети.Cast<УчастокСети>().Where(x => x.GetStatus() != ObjectStatus.Deleted);
            foreach (УчастокСети z in участки)
            {
                z.ИнфоОбУчасткеСети = "Адрес: " + z.ОбъектТеплопотребления.Здание.Адрес + "; Название ОТ: " +
                    z.ОбъектТеплопотребления.Название + "; Номер: " + z.Номер + "; Тип изоляции: " + z.ТипИзоляции + ";";
            }

            return new ICSSoft.STORMNET.DataObject[0];
            // *** End programmer edit section *** (OnUpdateОбъектТеплопотребления)
        }
    }
}