//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Task5
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// ОбъектТеплопотребления.
    /// </summary>
    // *** Start programmer edit section *** (ОбъектТеплопотребления CustomAttributes)

    // *** End programmer edit section *** (ОбъектТеплопотребления CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    public class ОбъектТеплопотребления : ICSSoft.STORMNET.DataObject
    {
        
        private string fНазвание;
        
        private string fДатаУстановки;
        
        private string fТипОТ;
        
        private int fТепловаяНагрузка;
        
        private IIS.Task5.Потребитель fПотребитель;
        
        private IIS.Task5.Здание fЗдание;
        
        private IIS.Task5.DetailArrayOfУчастокСети fУчастокСети;
        
        // *** Start programmer edit section *** (ОбъектТеплопотребления CustomMembers)

        // *** End programmer edit section *** (ОбъектТеплопотребления CustomMembers)

        
        /// <summary>
        /// Название.
        /// </summary>
        // *** Start programmer edit section *** (ОбъектТеплопотребления.Название CustomAttributes)

        // *** End programmer edit section *** (ОбъектТеплопотребления.Название CustomAttributes)
        [StrLen(255)]
        public virtual string Название
        {
            get
            {
                // *** Start programmer edit section *** (ОбъектТеплопотребления.Название Get start)

                // *** End programmer edit section *** (ОбъектТеплопотребления.Название Get start)
                string result = this.fНазвание;
                // *** Start programmer edit section *** (ОбъектТеплопотребления.Название Get end)

                // *** End programmer edit section *** (ОбъектТеплопотребления.Название Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ОбъектТеплопотребления.Название Set start)

                // *** End programmer edit section *** (ОбъектТеплопотребления.Название Set start)
                this.fНазвание = value;
                // *** Start programmer edit section *** (ОбъектТеплопотребления.Название Set end)

                // *** End programmer edit section *** (ОбъектТеплопотребления.Название Set end)
            }
        }
        
        /// <summary>
        /// ДатаУстановки.
        /// </summary>
        // *** Start programmer edit section *** (ОбъектТеплопотребления.ДатаУстановки CustomAttributes)

        // *** End programmer edit section *** (ОбъектТеплопотребления.ДатаУстановки CustomAttributes)
        [StrLen(255)]
        public virtual string ДатаУстановки
        {
            get
            {
                // *** Start programmer edit section *** (ОбъектТеплопотребления.ДатаУстановки Get start)

                // *** End programmer edit section *** (ОбъектТеплопотребления.ДатаУстановки Get start)
                string result = this.fДатаУстановки;
                // *** Start programmer edit section *** (ОбъектТеплопотребления.ДатаУстановки Get end)

                // *** End programmer edit section *** (ОбъектТеплопотребления.ДатаУстановки Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ОбъектТеплопотребления.ДатаУстановки Set start)

                // *** End programmer edit section *** (ОбъектТеплопотребления.ДатаУстановки Set start)
                this.fДатаУстановки = value;
                // *** Start programmer edit section *** (ОбъектТеплопотребления.ДатаУстановки Set end)

                // *** End programmer edit section *** (ОбъектТеплопотребления.ДатаУстановки Set end)
            }
        }
        
        /// <summary>
        /// ТипОТ.
        /// </summary>
        // *** Start programmer edit section *** (ОбъектТеплопотребления.ТипОТ CustomAttributes)

        // *** End programmer edit section *** (ОбъектТеплопотребления.ТипОТ CustomAttributes)
        [StrLen(255)]
        public virtual string ТипОТ
        {
            get
            {
                // *** Start programmer edit section *** (ОбъектТеплопотребления.ТипОТ Get start)

                // *** End programmer edit section *** (ОбъектТеплопотребления.ТипОТ Get start)
                string result = this.fТипОТ;
                // *** Start programmer edit section *** (ОбъектТеплопотребления.ТипОТ Get end)

                // *** End programmer edit section *** (ОбъектТеплопотребления.ТипОТ Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ОбъектТеплопотребления.ТипОТ Set start)

                // *** End programmer edit section *** (ОбъектТеплопотребления.ТипОТ Set start)
                this.fТипОТ = value;
                // *** Start programmer edit section *** (ОбъектТеплопотребления.ТипОТ Set end)

                // *** End programmer edit section *** (ОбъектТеплопотребления.ТипОТ Set end)
            }
        }
        
        /// <summary>
        /// ТепловаяНагрузка.
        /// </summary>
        // *** Start programmer edit section *** (ОбъектТеплопотребления.ТепловаяНагрузка CustomAttributes)

        // *** End programmer edit section *** (ОбъектТеплопотребления.ТепловаяНагрузка CustomAttributes)
        public virtual int ТепловаяНагрузка
        {
            get
            {
                // *** Start programmer edit section *** (ОбъектТеплопотребления.ТепловаяНагрузка Get start)

                // *** End programmer edit section *** (ОбъектТеплопотребления.ТепловаяНагрузка Get start)
                int result = this.fТепловаяНагрузка;
                // *** Start programmer edit section *** (ОбъектТеплопотребления.ТепловаяНагрузка Get end)

                // *** End programmer edit section *** (ОбъектТеплопотребления.ТепловаяНагрузка Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ОбъектТеплопотребления.ТепловаяНагрузка Set start)

                // *** End programmer edit section *** (ОбъектТеплопотребления.ТепловаяНагрузка Set start)
                this.fТепловаяНагрузка = value;
                // *** Start programmer edit section *** (ОбъектТеплопотребления.ТепловаяНагрузка Set end)

                // *** End programmer edit section *** (ОбъектТеплопотребления.ТепловаяНагрузка Set end)
            }
        }
        
        /// <summary>
        /// ОбъектТеплопотребления.
        /// </summary>
        // *** Start programmer edit section *** (ОбъектТеплопотребления.Потребитель CustomAttributes)

        // *** End programmer edit section *** (ОбъектТеплопотребления.Потребитель CustomAttributes)
        [PropertyStorage(new string[] {
                "Потребитель"})]
        [NotNull()]
        public virtual IIS.Task5.Потребитель Потребитель
        {
            get
            {
                // *** Start programmer edit section *** (ОбъектТеплопотребления.Потребитель Get start)

                // *** End programmer edit section *** (ОбъектТеплопотребления.Потребитель Get start)
                IIS.Task5.Потребитель result = this.fПотребитель;
                // *** Start programmer edit section *** (ОбъектТеплопотребления.Потребитель Get end)

                // *** End programmer edit section *** (ОбъектТеплопотребления.Потребитель Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ОбъектТеплопотребления.Потребитель Set start)

                // *** End programmer edit section *** (ОбъектТеплопотребления.Потребитель Set start)
                this.fПотребитель = value;
                // *** Start programmer edit section *** (ОбъектТеплопотребления.Потребитель Set end)

                // *** End programmer edit section *** (ОбъектТеплопотребления.Потребитель Set end)
            }
        }
        
        /// <summary>
        /// ОбъектТеплопотребления.
        /// </summary>
        // *** Start programmer edit section *** (ОбъектТеплопотребления.Здание CustomAttributes)

        // *** End programmer edit section *** (ОбъектТеплопотребления.Здание CustomAttributes)
        [PropertyStorage(new string[] {
                "Здание"})]
        [NotNull()]
        public virtual IIS.Task5.Здание Здание
        {
            get
            {
                // *** Start programmer edit section *** (ОбъектТеплопотребления.Здание Get start)

                // *** End programmer edit section *** (ОбъектТеплопотребления.Здание Get start)
                IIS.Task5.Здание result = this.fЗдание;
                // *** Start programmer edit section *** (ОбъектТеплопотребления.Здание Get end)

                // *** End programmer edit section *** (ОбъектТеплопотребления.Здание Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ОбъектТеплопотребления.Здание Set start)

                // *** End programmer edit section *** (ОбъектТеплопотребления.Здание Set start)
                this.fЗдание = value;
                // *** Start programmer edit section *** (ОбъектТеплопотребления.Здание Set end)

                // *** End programmer edit section *** (ОбъектТеплопотребления.Здание Set end)
            }
        }
        
        /// <summary>
        /// ОбъектТеплопотребления.
        /// </summary>
        // *** Start programmer edit section *** (ОбъектТеплопотребления.УчастокСети CustomAttributes)

        // *** End programmer edit section *** (ОбъектТеплопотребления.УчастокСети CustomAttributes)
        public virtual IIS.Task5.DetailArrayOfУчастокСети УчастокСети
        {
            get
            {
                // *** Start programmer edit section *** (ОбъектТеплопотребления.УчастокСети Get start)

                // *** End programmer edit section *** (ОбъектТеплопотребления.УчастокСети Get start)
                if ((this.fУчастокСети == null))
                {
                    this.fУчастокСети = new IIS.Task5.DetailArrayOfУчастокСети(this);
                }
                IIS.Task5.DetailArrayOfУчастокСети result = this.fУчастокСети;
                // *** Start programmer edit section *** (ОбъектТеплопотребления.УчастокСети Get end)

                // *** End programmer edit section *** (ОбъектТеплопотребления.УчастокСети Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ОбъектТеплопотребления.УчастокСети Set start)

                // *** End programmer edit section *** (ОбъектТеплопотребления.УчастокСети Set start)
                this.fУчастокСети = value;
                // *** Start programmer edit section *** (ОбъектТеплопотребления.УчастокСети Set end)

                // *** End programmer edit section *** (ОбъектТеплопотребления.УчастокСети Set end)
            }
        }
    }
}
