//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Task5
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Потребитель.
    /// </summary>
    // *** Start programmer edit section *** (Потребитель CustomAttributes)

    // *** End programmer edit section *** (Потребитель CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    public class Потребитель : ICSSoft.STORMNET.DataObject
    {
        
        private string fНазваниеКомпании;
        
        private string fФИОРуководителя;
        
        private string fЮридическийАдрес;
        
        private int fЛицевойСчёт;
        
        // *** Start programmer edit section *** (Потребитель CustomMembers)

        // *** End programmer edit section *** (Потребитель CustomMembers)

        
        /// <summary>
        /// НазваниеКомпании.
        /// </summary>
        // *** Start programmer edit section *** (Потребитель.НазваниеКомпании CustomAttributes)

        // *** End programmer edit section *** (Потребитель.НазваниеКомпании CustomAttributes)
        [StrLen(255)]
        public virtual string НазваниеКомпании
        {
            get
            {
                // *** Start programmer edit section *** (Потребитель.НазваниеКомпании Get start)

                // *** End programmer edit section *** (Потребитель.НазваниеКомпании Get start)
                string result = this.fНазваниеКомпании;
                // *** Start programmer edit section *** (Потребитель.НазваниеКомпании Get end)

                // *** End programmer edit section *** (Потребитель.НазваниеКомпании Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Потребитель.НазваниеКомпании Set start)

                // *** End programmer edit section *** (Потребитель.НазваниеКомпании Set start)
                this.fНазваниеКомпании = value;
                // *** Start programmer edit section *** (Потребитель.НазваниеКомпании Set end)

                // *** End programmer edit section *** (Потребитель.НазваниеКомпании Set end)
            }
        }
        
        /// <summary>
        /// ФИОРуководителя.
        /// </summary>
        // *** Start programmer edit section *** (Потребитель.ФИОРуководителя CustomAttributes)

        // *** End programmer edit section *** (Потребитель.ФИОРуководителя CustomAttributes)
        [StrLen(255)]
        public virtual string ФИОРуководителя
        {
            get
            {
                // *** Start programmer edit section *** (Потребитель.ФИОРуководителя Get start)

                // *** End programmer edit section *** (Потребитель.ФИОРуководителя Get start)
                string result = this.fФИОРуководителя;
                // *** Start programmer edit section *** (Потребитель.ФИОРуководителя Get end)

                // *** End programmer edit section *** (Потребитель.ФИОРуководителя Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Потребитель.ФИОРуководителя Set start)

                // *** End programmer edit section *** (Потребитель.ФИОРуководителя Set start)
                this.fФИОРуководителя = value;
                // *** Start programmer edit section *** (Потребитель.ФИОРуководителя Set end)

                // *** End programmer edit section *** (Потребитель.ФИОРуководителя Set end)
            }
        }
        
        /// <summary>
        /// ЮридическийАдрес.
        /// </summary>
        // *** Start programmer edit section *** (Потребитель.ЮридическийАдрес CustomAttributes)

        // *** End programmer edit section *** (Потребитель.ЮридическийАдрес CustomAttributes)
        [StrLen(255)]
        public virtual string ЮридическийАдрес
        {
            get
            {
                // *** Start programmer edit section *** (Потребитель.ЮридическийАдрес Get start)

                // *** End programmer edit section *** (Потребитель.ЮридическийАдрес Get start)
                string result = this.fЮридическийАдрес;
                // *** Start programmer edit section *** (Потребитель.ЮридическийАдрес Get end)

                // *** End programmer edit section *** (Потребитель.ЮридическийАдрес Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Потребитель.ЮридическийАдрес Set start)

                // *** End programmer edit section *** (Потребитель.ЮридическийАдрес Set start)
                this.fЮридическийАдрес = value;
                // *** Start programmer edit section *** (Потребитель.ЮридическийАдрес Set end)

                // *** End programmer edit section *** (Потребитель.ЮридическийАдрес Set end)
            }
        }
        
        /// <summary>
        /// ЛицевойСчёт.
        /// </summary>
        // *** Start programmer edit section *** (Потребитель.ЛицевойСчёт CustomAttributes)

        // *** End programmer edit section *** (Потребитель.ЛицевойСчёт CustomAttributes)
        public virtual int ЛицевойСчёт
        {
            get
            {
                // *** Start programmer edit section *** (Потребитель.ЛицевойСчёт Get start)

                // *** End programmer edit section *** (Потребитель.ЛицевойСчёт Get start)
                int result = this.fЛицевойСчёт;
                // *** Start programmer edit section *** (Потребитель.ЛицевойСчёт Get end)

                // *** End programmer edit section *** (Потребитель.ЛицевойСчёт Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Потребитель.ЛицевойСчёт Set start)

                // *** End programmer edit section *** (Потребитель.ЛицевойСчёт Set start)
                this.fЛицевойСчёт = value;
                // *** Start programmer edit section *** (Потребитель.ЛицевойСчёт Set end)

                // *** End programmer edit section *** (Потребитель.ЛицевойСчёт Set end)
            }
        }
    }
}
