/*flexberryautogenerated="true"*/
namespace IIS.ThermoObject
{
    using System;
    using ICSSoft.STORMNET.Web.Controls;

    using Resources;

    public partial class СетевойРайонL : BaseListForm<СетевойРайон>
    {
        /// <summary>
        /// Конструктор без параметров,
        /// инициализирует свойства, соответствующие конкретной форме.
        /// </summary>
        public СетевойРайонL() : base(СетевойРайон.Views.СетевойРайонL)
        {
            EditPage = СетевойРайонE.FormPath;
        }
                
        /// <summary>
        /// Путь до формы.
        /// </summary>
        public static string FormPath
        {
            get { return "~/forms/SetevojRajon/SetevojRajonL.aspx"; }
        }

        /// <summary>
        /// Вызывается самым первым в Page_Load.
        /// </summary>
        protected override void Preload()
        {
        }

        /// <summary>
        /// Вызывается самым последним в Page_Load.
        /// </summary>
        protected override void Postload()
        {
        }
    }
}
