//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.ThermoObject
{
    using System;
    using System.Xml;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Типы прокладки.
    /// </summary>
    // *** Start programmer edit section *** (ТипыПрокладки CustomAttributes)

    // *** End programmer edit section *** (ТипыПрокладки CustomAttributes)
    public enum ТипыПрокладки
    {
        
        /// <summary>
        /// 
        /// </summary>
        // *** Start programmer edit section *** (ТипыПрокладки.Внутренняя CustomAttributes)

        // *** End programmer edit section *** (ТипыПрокладки.Внутренняя CustomAttributes)
        Внутренняя,
        
        /// <summary>
        /// 
        /// </summary>
        // *** Start programmer edit section *** (ТипыПрокладки.Внешняя CustomAttributes)

        // *** End programmer edit section *** (ТипыПрокладки.Внешняя CustomAttributes)
        Внешняя,
    }
}
